- name: Install Node
  command: brew install node
  tags:
    - node
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
- name: Install Node 14
  shell: nvm install 14
  tags:
    - node
