- name: Install ZSH
  command: brew install zsh
  tags:
    - zsh
- name: Make ZSH default shell
  command: chsh -s /bin/zsh
  tags:
    - zsh
- name: Install OhMyZsh
  command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: Enable zsh-autosuggestions plugin
  lineinfile:
    dest: "~/.zshrc"
    line: plugins+=(zsh-autosuggestions)
    create: yes
  tags:
    - zsh
