name: Test Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Tasks
    runs-on: macos-12

    steps:
      - name: Checkout project code
        uses: actions/checkout@v2.4.0

      - name: Test the playbook
        run: ansible-playbook main.yml
