name: Test Setup

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Tasks
    runs-on: macos-12

    steps:
      - name: Checkout project code
        uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Ansible
        run: |
          python -m pip install ansible
      - name: Test the playbook
        run: ansible-playbook ../main.yml
